import Head from "next/head";
import Image from "next/image";
import girl from "../public/girl.png";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-[calc(100vh-112px)]">
        <div className="container flex h-full mx-auto justify-center items-center px-16 py-16">
          <div className="container flex rounded-2xl bg-back px-5 py-5 h-72 w-4/5">
            <div className="flex-1">
              <div className="flex-1 w-48 mb-8">
                <h1 className="text-center font-qs font-semibold whitespace-nowrap text-xl">
                  Selamat Datang di Lost and Found!
                </h1>
              </div>
              <div className="flex-1">
                <h1 className="font-qs font-bold xl:text-5xl lg:text-4xl text-3xl">
                  Yuk, bantu kami mencari barang yang
                </h1>
                <div className="w-40">
                  <h1 className="font-qs font-bold xl:text-5xl lg:text-4xl text-3xl underline decoration-double">
                    hilang!
                  </h1>
                  {/* <div className="bg-red-300 h-1/5 w-1/5"></div> */}
                </div>
              </div>
            </div>
            <div className="flex w-3/5 relative">
              <Image src={girl} layout="fill" objectFit="contain" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
